apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-analyzer
spec:
  selector:
    matchLabels:
      run: stream-analyzer
  replicas: 1
  template:
    metadata:
      labels:
        run: stream-analyzer
    spec:
      containers:
      - name: stream-analyzer
        image: pawelzakieta/aui:stream-analyzer
        ports:
        - containerPort: 5000
          name: http
        imagePullPolicy: Always
