apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp
  labels:
    run: nginx-rtmp
spec:
  type: NodePort
  ports:
  - port: 1935
    name: rtmp
    targetPort: 1935
    nodePort: 30000
    protocol: TCP
  - port: 80
    name: http
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  selector:
    run: nginx-rtmp